### ISSUE TITLE
How to run/use this code?

### ISSUE THREAD

**Issue by nickedes** [shiba24/learning2rank#7]
I did the following : 
```
$ git clone  https://github.com/shiba24/learning2rank.git
$ python learning2rank/__init__.py
Traceback (most recent call last):
  File "learning2rank/__init__.py", line 1, in <module>
    import utils, rank, regression
  File "/mnt/E4481D43481D1640/Various/books/ML-Course/pw/learning2rank/rank/__init__.py", line 1, in <module>
    import ListNet, RankNet
ModuleNotFoundError: No module named 'ListNet'

```

Shows this error.

What should I do?

**Comment by alejandromorrison** [comment]
I have sure that if you want to initialize the repositor in excellence says in the README.md

that you'll only need to use 
<code>from learning2rank.rank import RankNet</code>
<code>Model = RankNet.RankNet()</code>

**Comment by shiba24** [comment]
Thank you @alejandromorrison ! :)
